export const platformOptions = [
  "github",
  "linkedin",
  "instagram",
  "facebook",
  "twitter",
  "reddit",
  "resume",
];

export const tags = [
"Andhra Pradesh government", 
"Arunachal Pradesh government",
"Assam government",
"Bihar government", 
"Chhattisgarh government" ,
"Goa government" ,
"Gujarat government", 
"Haryana government",
"Himachal Pradesh government", 
"Jharkhand government" ,
"Karnataka government",
"Kerala government" ,
"Madhya Pradesh government",
"Maharashtra government",
"Manipur government" ,
"Meghalaya government" ,
"Mizoram government" ,
"Nagaland government" ,
"Odisha government",
"Punjab government", 
"Rajasthan government" ,
"Sikkim government" ,
"Tamil Nadu government", 
"Telangana government" ,
"Tripura government" ,
"Uttar Pradesh government", 
"Uttarakhand government" ,
"West Bengal government",
"Category General",
"Category PWD",
"Category OBC",
"Category SC",
"Category ST",
"Category EWS",
"High School",
"PostMatric",
"PreMatric",
"Associate degree",
"Bachelor's degree",
"Master's degree",
"Ph.D.",
"Diploma",
  
  

];
