# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Node.js app to Azure Web App - Scholarease

on:
  push:
    branches:
      - master # Trigger only on the "master" branch
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Production"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Scholarease"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F4F383842EEF418B9844C1785B6F62D8 }}
          package: ./backend
